### PR TITLE
Fix missed notification in Mutex example

### LINKED ISSUE #143: This seems actually not stable(Dead lock)
https://github.com/beckend/event-listener/tree/event_listener_bug

`cargo run --release --example mutex`

https://github.com/beckend/event-listener/blob/event_listener_bug/examples/mutex.rs#L127-L151

It dead locks.

### PR DESCRIPTION
**Pull request by notgull**
I forgot to run notify() when I rewrote this example without unsafe
code. It looks like it prevents deadlocks in this mutex implementation.

I believe this fixes #143. @beckend Can you confirm?

### CODE REVIEW

File: examples/mutex.rs [hunk 1]
```diff
@@ -107,19 +110,29 @@ mod example {
     }
 
     /// A guard holding a lock.
-    struct MutexGuard<'a, T>(Locked<'a, T>);
+    struct MutexGuard<'a, T> {
+        mutex: &'a Mutex<T>,
```
Comment (fogti) [inline examples/mutex.rs:114]: Given that we only access `mutex.lock_ops`, wouldn't it be more appropriate to just place a pointer to `lock_ops` here?

**Review by fogti — APPROVED** [review]
